#admin用のコンテナ
FROM ruby:3.1.3 as admin

RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    npm \
    node.js \
    postgresql-client \
    yarn
WORKDIR /admin
COPY /admin/Gemfile /admin/Gemfile.lock ./
RUN bundle install
COPY . /admin/

CMD [ "rails", "s", "-p", "3001", "-b", "0.0.0.0" ]

