#api用のコンテナ
FROM ruby:3.1.3 as api

RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    node.js \
    postgresql-client \
    yarn
WORKDIR /api
COPY api/Gemfile api/Gemfile.lock ./
RUN bundle install
COPY . /api/
