name: admin
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install docker-compose
        uses: docker-compose -f docker-compose-ci.yml up -d
        
      - name: Rails test
        run: |
          docker-compose exec admin rails db:create
          docker-compose exec admin rails db:migrate
          docker-compose exec admin rails test





  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #     - name: Install Ruby and gems
  #       uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
  #       with:
  #         bundler-cache: true
  #     # Add or replace any other lints here
  #     - name: Security audit dependencies
  #       run: bin/bundler-audit --update
  #     - name: Security audit application code
  #       run: bin/brakeman -q -w2
  #     - name: Lint Ruby files
  #       run: bin/rubocop --parallel
