name: admin
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      # - name: Install Docker composer
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y docker-compose

      - name: Install docker-compose
        run: docker-compose -f docker-compose-ci.yml up -d
        
      - name: Rails test
        run: |
          docker-compose exec -T admin rails db:create
          docker-compose exec -T admin rails db:migrate
          docker-compose exec -T admin rails test
     
