name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy-admin:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repository
          uses: actions/checkout@v2
   
        # - name: Login heroku
        #   run: docker login -u ${{secrets.HEROKU_USERNAME}} -p ${{secrets.HEROKU_API_KEY}} registry.heroku.com 

        # - name: Set up Docker build context #build contextにプロジェクトファイルの全てを移動する
        #   run: cp -R admin/* .
        
        # - name: build and push Docker image
        #   run: |
        #     docker build -t registry.heroku.com/${{secrets.HEROKU_APP_NAME}}/admin -f Dockerfile.admin .
        #     docker push registry.heroku.com/${{secrets.HEROKU_APP_NAME}}/admin:latest

        - name: Deploy to heroku AkihileshNS
          uses: akhileshns/heroku-deploy@v3.12.14 # This is the action
          with:
             heroku_api_key: ${{secrets.HEROKU_API_KEY}}
             heroku_app_name: ${{secrets.HEROKU_APP_NAME}} #Must be unique in Heroku
             heroku_email: ${{secrets.HEROKU_EMAIL}}
             branch: "main"
             usedocker: true
             docker_heroku_process_type: "web"
             appdir: "${{secrets.HEROKU_APP_NAME}}/admin"
             healthcheck: "https:://${{secrets.HEROKU_APP_NAME}}.herokuapp.com/health"
             dontuseforce: true
                
        - name: rails migrate
          run: heroku run --app ${{secrets.HEROKU_APP_NAME}}/admin rails db:migrate

  # deploy-api:
  #   runs-on: ubuntu-latest
  #   steps:
  #       - name: Checkout repository
  #         uses: actions/checkout@v2

  #       - name: Login heroku
  #         run: docker login -u ${{secrets.HEROKU_USERNAME}} -p ${{secrets.HEROKU_API_KEY}} registry.heroku.com 

  #       - name: Set up Docker build context #build contextにプロジェクトファイルの全てを移動する
  #         run: |
  #           cp -R api/* .
  #           cp -R frontend/* .
        
  #       - name: build and push Docker image
  #         run: |
  #           docker build -t registry.heroku.com/${{secrets.HEROKU_APP_NAME}}/admin -f Dockerfile.admin .
  #           docker build -t registry.heroku.com/${{secrets.HEROKU_APP_NAME}}/api -f Dockerfile.api .
  #           docker build -t registry.heroku.com/${{secrets.HEROKU_APP_NAME}}/frontend -f Dockerfile.frontend .
  #           docker push registry.heroku.com/${{secrets.HEROKU_APP_NAME}}/admin:latest
  #           docker push registry.heroku.com/${{secrets.HEROKU_APP_NAME}}/api:latest
  #           docker push registry.heroku.com/${{secrets.HEROKU_APP_NAME}}/frontend
        

        # - name: Deploy to Heroku
        #   run:  |
        #     heroku container:release web --app ${{secrets.HEROKU_APP_NAME}}
        #     # heroku container:release web --app ${{secrets.HEROKU_APP_NAME}}/api
        #     # heroku container:release web --app ${{secrets.HEROKU_APP_NAME}}/frontend