name: deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repository
          uses: actions/checkout@v2
   
        - name: Set up Heroku
          uses: akhileshns/heroku-deploy@v3.12.14
          with:
            heroku_api_key: ${{secrets.HEROKU_API_KEY}}
            heroku_app_name: "loto-searcher"
            heroku_email: ${{secrets.HEROKU_EMAIL}} 
            usedocker: true
