name: deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repository
          uses: actions/checkout@v2
   
        - name: Login heroku
          run: docker login -u ${{secrets.HEROKU_USERNAME}} -p ${{secrets.HEROKU_API_KEY}} registry.heroku.com 

        - name: Set up Docker build context #build contextにプロジェクトファイルの全てを移動する
          run: |
            mv loto-searcher/* .
            mv loto-searcher/.dockerignore .
        
        - name: build and push Docker image
          run: |
            docker build -t registry.heroku.com/${{secrets.HEROKU_APP_NAME}} -f Dockerfile.prod .
            docker push registry.heroku.com/${{secrets.HEROKU_APP_NAME}}

        - name: Deploy to Heroku
          run:  heroku container:release web --app ${{secrets.HEROKU_APP_NAME}}
        
        - name: rails migrate
          run: heroku run --app ${{secrets.HEROKU_APP_NAME}} rails db:migrate