name: deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repository
          uses: actions/checkout@v2
   
        - name: Login heroku
          run: docker login -u ${{secrets.HEROKU_USERNAME}} -p ${{secrets.HEROKU_API_KEY}} registry.heroku.com 

        - name: Set up Docker build context #build contextにプロジェクトファイルの全てを移動する
          run: |
            cp -R admin/* .
            cp -R api/* .
            cp -R frontend/* .
        
        - name: build and push Docker image
          run: |
            docker build -t registry.heroku.com/${{secrets.HEROKU_APP_NAME}}/admin -f Dockerfile.admin .
            docker build -t registry.heroku.com/${{secrets.HEROKU_APP_NAME}}/api -f Dockerfile.api .
            docker build -t registry.heroku.com/${{secrets.HEROKU_APP_NAME}}/frontend -f Dockerfile.frontend .
            docker push registry.heroku.com/${{secrets.HEROKU_APP_NAME}}/admin
            docker push registry.heroku.com/${{secrets.HEROKU_APP_NAME}}/api
            docker push registry.heroku.com/${{secrets.HEROKU_APP_NAME}}/frontend

        # - name: Deploy to Heroku
        #   run:  |
        #     heroku container:release web --app ${{secrets.HEROKU_APP_NAME}}/admin
        #     heroku container:release web --app ${{secrets.HEROKU_APP_NAME}}/api
        #     heroku container:release web --app ${{secrets.HEROKU_APP_NAME}}/frontend
        
        - name: rails migrate
          run: heroku run --app ${{secrets.HEROKU_APP_NAME}}/admin rails db:migrate
        
        # - name: rails server
        #   run: heroku run --app ${{secrets.HEROKU_APP_NAME}}/admin rails s -p 3001 -b 0.0.0.0