name: deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repository
          uses: actions/checkout@v2
   
        - name: Login heroku
          run: docker login -u ${{secrets.HEROKU_USERNAME}} -p ${{secrets.HEROKU_API_KEY}} registry.heroku.com 
        
        - name: build docker
          run: |
            docker build -t registry.heroku.com/${{secrets.HEROKU_APP_NAME}}/admin -f Dockerfile.prod .
            docker push registry.heroku.com/${{secrets.HEROKU_APP_NAME}}/admin
            heroku run --app ${{secrets.HEROKU_APP_NAME}} rails db:migrate